wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-05
batch_size:
  desc: null
  value: 64
num_epochs:
  desc: null
  value: 100
num_train_samples:
  desc: null
  value: 640
num_test_samples:
  desc: null
  value: 128
warmup_steps:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.43.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723228050
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      3:
      - 13
      - 16
      - 23
      - 61
      4: 3.8.19
      5: 0.17.5
      6: 4.43.3
      8:
      - 5
      13: linux-x86_64
